name: generative_ai
description: A package that provides a high-level API for interacting with Generative AI API
version: 1.0.0
repository: https://github.com/lenzpaul/generative_ai

environment:
  sdk: ^3.4.1

 
dependencies:
  google_generative_ai: ^0.4.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
